trigger:
  branches:
    include:
      - master

resources:
- repo: self

variables:
  - name: hello
    value: world
  - group: nuget


stages:
- stage: Main
  displayName: Build image
  jobs:  
  - job: Publish
    displayName: Publish NuGet Package
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet build
      displayName: Build the sln
    - script: ./pack.sh
      displayName: Pack NuGet
    - script: dotnet nuget push client/bin/Release/*.nupkg -k $API_KEY -s https://api.nuget.org/v3/index.json
      displayName: Push to NuGet
      env:
        API_KEY: $(NugetApiKey)
