trigger:
  branches:
    include:
      - master

resources:
- repo: self

variables:
  - name: hello
    value: world


stages:
- stage: Main
  displayName: Build image
  variables:
    group: nuget
  jobs:  
  - job: Publish
    displayName: Publish NuGet Package
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet build
      displayName: Build the sln
    - script: ./pack.sh
      displayName: Pack the NuGet
    - script: dotnet nuget push client/bin/Release/*.nupkg -k $API_KEY -s https://api.nuget.org/v3/index.json
      env:
        API_KEY: $(NugetApiKey)
