version: "3"
services:
  generator:
    image: openapitools/openapi-generator-cli
    volumes: 
      - ${PWD}:/local
    command: generate -i https://beta.amphoradata.com/swagger/v1/swagger.json -g csharp-netcore -o /local/generated --additional-properties=packageName=AmphoraData.Client,packageVersion=0.0.1,targetFramework=netstandard2.0